### ISSUE TITLE
Extending the levels

### ISSUE THREAD

**Issue by The-Galaxian** [fawtytoo/ManicMiner#4]
I have recently started playing this extended version of Manic Miner

Did you use any tools to map the original levels to your remake?

https://jswmm.co.uk/files/file/173-manic-miner-deeper-and-down/

I would be interested in adding these extra levels

**Comment by fawtytoo** [comment]
I think this would be more suited to a separate project.

**Comment by fawtytoo** [comment]
Closing as unsuitable for this project.
